### ISSUE TITLE
Question: Is this have multiple account support? 

### ISSUE THREAD

**Issue by jinxx0** [FrozenTear7/twitch-spambot#1]
For spam

**Comment by FrozenTear7** [comment]
I didn't mean for this to become a multi account spam program and I won't be adding support for that, but you could pretty much create a separate directory for each account you intend to run the script on. Then create a batch file that launches ```npm start``` on each directory. 
I guess this could be doable if you want to spam on a couple accounts, but not if it would be like 50+.
