### ISSUE TITLE
Fail to Fetch All Global Emotes

### ISSUE THREAD

**Issue by KEKLBruh** [FrozenTear7/twitch-spambot#16]
Error: "Exception while fetching emotes: Request failed with status code 404"

**Screenshot**
https://i.imgur.com/ZY2pyp6.png

**Version**
v1.5.2

**Comment by FrozenTear7** [comment]
Can you show me your `config/whitelistEmotes.json` file? If the error persists, I suspect you might have added an invalid channel ID in there and that's the reason for the 404 error.

**Not relevant anymore**

**Comment by FrozenTear7** [comment]
Actually got that same error today and it seems like there are some problems with https://www.twitchemotes.com/ from where I fetch emotes. The problem went away after a minute or so and then the bot was working fine.
Just restart it after a while, there's nothing I can do about the problem.
